inputs:
  version:
    description: "A version to install ecspresso"
    default: "v1.3.2"
runs:
  using: "composite"
  steps:
    - run: |
        if [ ${{ inputs.version }} = "latest" ]; then
          FILENAME=$(curl -sS https://api.github.com/repos/kayac/ecspresso/releases/latest|jq -r '.assets[].name|select(test("linux-amd64$"))')
          DOWNLOAD_URL=https://github.com/kayac/ecspresso/releases/latest/download/${FILENAME}.zip
        else
          FILENAME=ecspresso-${{ inputs.version }}-linux-amd64
          DOWNLOAD_URL=https://github.com/kayac/ecspresso/releases/download/${{ github.event.inputs.version }}/${FILENAME}.zip
        fi
        cd /tmp
        curl -sLO ${DOWNLOAD_URL}
        unzip ${FILENAME}
        sudo install ${FILENAME} /usr/local/bin/ecspresso
        rm -f ${FILENAME} ${FILENAME}.zip
        /usr/local/bin/ecspresso version
      shell: bash
