inputs:
  version:
    description: "A version to install ecspresso"
    default: "v1.3.2"
runs:
  using: "composite"
  steps:
    - run: |
        set -e
        VERSION="${{ inputs.version }}"
        if [ "${VERSION}" = "latest" ]; then
          DOWNLOAD_URL=$(curl -sS https://api.github.com/repos/kayac/ecspresso/releases/latest|jq -r '.assets[].browser_download_url|select(test("linux-amd64.zip$"))')
        else
          DOWNLOAD_URL=https://github.com/kayac/ecspresso/releases/download/${VERSION}/ecspresso-${VERSION}-linux-amd64.zip
        fi
        cd /tmp
        curl -sfLO ${DOWNLOAD_URL}
        FILENAME=$(basename $DOWNLOAD_URL .zip)
        unzip ${FILENAME}.zip
        sudo install ${FILENAME} /usr/local/bin/ecspresso
        rm -f ${FILENAME} ${FILENAME}.zip
        /usr/local/bin/ecspresso version
      shell: bash
