name: test action
on:
  push:
    branches:
      - v1
  workflow_dispatch:

jobs:
  install:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: kayac/ecspresso@v0
        with:
          version: v1.5.0
      - run: |
          ecspresso version 2>&1 | fgrep -q v1.5.0
      - uses: kayac/ecspresso@v0
        with:
          version: latest
      - run: |
          ecspresso version
